version: "2.4"

services:

  plugin-builder:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - plugin-dist:/app/apps/kitchensink/dist
    command: sh -c "npm install -g pnpm && pnpm i && pnpm build:kitchensink"

  plugin-server:
    image: nginx:alpine
    volumes:
      - plugin-dist:/usr/share/nginx/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/mock:/usr/share/nginx/html/mock # Serve mock audio file for testing
    ports:
      - "9001:80"
    networks:
      - dataverse
    depends_on:
      plugin-builder:
        condition: service_completed_successfully

  plugin-injector:
    user: root
    image: curlimages/curl:latest
    volumes:
      - plugin-dist:/plugin-dist
      - ./docker/branding:/branding
      - ./docker/scripts/inject.sh:/inject.sh
    command: sh /inject.sh
    networks:
      - dataverse
    depends_on:
      plugin-builder:
        condition: service_completed_successfully
      bootstrap:
        condition: service_completed_successfully

  dataverse:
    container_name: "dataverse"
    hostname: dataverse
    image: gdcc/dataverse:latest
    restart: on-failure
    user: payara
    environment:
      DATAVERSE_SITEURL: "http://${MACHINE_IP:-localhost}:8080"
      DATAVERSE_DB_HOST: postgres
      DATAVERSE_DB_PASSWORD: secret
      DATAVERSE_DB_USER: dataverse
      DATAVERSE_FEATURE_API_BEARER_AUTH: "1"
      JVM_ARGS: -Ddataverse.files.storage-driver-id=file1
        -Ddataverse.files.file1.type=file
        -Ddataverse.files.file1.label=Filesystem
        -Ddataverse.files.file1.directory=${STORAGE_DIR}/store
        -Ddataverse.pid.providers=perma1
        -Ddataverse.pid.default-provider=perma1
        -Ddataverse.pid.perma1.type=perma
        -Ddataverse.pid.perma1.label=Perma1
        -Ddataverse.pid.perma1.authority=DV
        -Ddataverse.pid.perma1.permalink.separator=/
    ports:
      - "8080:8080"
      - "4848:4848"
      - "9009:9009"
      - "8686:8686"
    networks:
      - dataverse
    depends_on:
      - postgres
      - solr
      - dv_initializer
    volumes:
      - ./data/app/data:/dv
      - ./data/app/secrets:/secrets
      - ./docker/branding:/var/www/dataverse/branding

  bootstrap:
    container_name: "bootstrap"
    image: gdcc/configbaker:latest
    restart: "no"
    environment:
      - TIMEOUT=3m
    command:
      - bootstrap.sh
      - demo
    networks:
      - dataverse

  dv_initializer:
    container_name: "dv_initializer"
    image: gdcc/configbaker:latest
    restart: "no"
    command:
      - sh
      - -c
      - "fix-fs-perms.sh dv"
    volumes:
      - ./data/app/data:/dv

  postgres:
    container_name: "postgres"
    hostname: postgres
    image: postgres:17
    restart: on-failure
    environment:
      - POSTGRES_USER=dataverse
      - POSTGRES_PASSWORD=secret
    networks:
      - dataverse
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data

  solr_initializer:
    container_name: "solr_initializer"
    image: gdcc/configbaker:latest
    restart: "no"
    command:
      - sh
      - -c
      - "fix-fs-perms.sh solr && cp -a /template/* /solr-template"
    volumes:
      - ./data/solr/data:/var/solr
      - ./data/solr/conf:/solr-template

  solr:
    container_name: "solr"
    hostname: "solr"
    image: solr:9.8.0
    depends_on:
      - solr_initializer
    restart: on-failure
    ports:
      - "8983:8983"
    environment:
      - SOLR_OPTS=-Dsolr.jetty.request.header.size=102400
    networks:
      - dataverse
    command:
      - "solr-precreate"
      - "collection1"
      - "/template"
    volumes:
      - ./data/solr/data:/var/solr
      - ./data/solr/conf:/template

volumes:
  plugin-dist:

networks:
  dataverse:
    driver: bridge